spring:
  application:
    name: cards
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8089

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html