spring:
  application:
    name: "cards"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
server:
  port: 9000

#get all api of ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

endpoint:
  shutdown:
    enabled: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "managing bank cards."
    version: "1.0.0"


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG