spring:
  application:
    name: cards
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  #config rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: "optional:configserver:http://localhost:8071/"
server:
  port: 9089

#get all api of ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html