spring:
  application:
    name: "accounts"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 9088

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

#accept all api actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"







springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
