spring:
  application:
    name: "accounts"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  config:
    import: "optional:configserver:http://localhost:8071/"

  #config rabbitmq
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"



server:
  port: 9088

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

#accept all api actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"







springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
