spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 9090
