apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb
  labels:
    app: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: LOANS_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: PASS_DB
          ports:
            - name: mysql
              containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
  labels:
    app: loansdb
spec:
  selector:
    app: loansdb
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306


