spring:
  application:
    name: accounts
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
      - "application_dev.yml"
  profiles:
    active: dev

server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
