spring:
  application:
   name: accounts
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
    show-sql: true
server:
 port: 8088