spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: "dev"

#accept all api actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9090
