services:
  accounts:
    image: "accounts:latest"
    container_name: "accounts-ms"
    ports:
      - "9088:9088"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices_network
  loans:
    image: "loans:latest"
    container_name: "loans-ms"
    ports:
      - "9089:9089"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices_network
  cards:
    image: "cards:s4"
    container_name: "cards-ms"
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices_network
networks:
  microservices_network:
    driver: bridge
