spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

logging:
  level:
    com:
      bank:
        gatewayserver: debug

#accept all api actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gatewayserver"
    description: "managing bank gatewayserver."
    version: "1.0.0"

